const baseSandwiches = [
  { file: "01_pan_bagnat.png", name: "Pan Bagnat", country: "France",
    desc: "Niçoise salad on a crusty round loaf, drenched in olive oil. From Nice in the South of France.",
    key: ["Crusty country loaf (pain de campagne)", "Canned tuna", "Anchovy fillets", "Black olives", "Hard-boiled eggs", "Tomato, cucumber, red onion", "Extra virgin olive oil — generously"] },
  { file: "02_bocadillo_iberico.png", name: "Bocadillo de Jamón Ibérico", country: "Spain",
    desc: "Spain's prized acorn-fed Iberian ham on crusty bread brushed with olive oil. Simple and luxurious.",
    key: ["Crusty baguette", "Jamón Ibérico, sliced thin", "Extra virgin olive oil", "Optional: fresh tomato", "Optional: manchego cheese"] },
  { file: "03_banh_mi.png", name: "Bánh Mì", country: "Vietnam",
    desc: "A French baguette reinvented in Vietnam — crunchy, fresh, savory, and now a global sensation.",
    key: ["Light airy baguette", "Grilled pork or chả lụa", "Pickled carrot & daikon", "Cucumber, cilantro, jalapeño", "Mayonnaise + Maggi sauce"] },
  { file: "04_torta_ahogada.png", name: "Torta Ahogada", country: "Mexico",
    desc: "Guadalajara's 'drowned' pork sandwich — crusty bread doused in spicy red chile sauce.",
    key: ["Birote or bolillo roll", "Carnitas (chopped pork)", "Guajillo chile sauce", "Pickled onion, lime"] },
  { file: "05_tramezzino.png", name: "Tramezzino", country: "Italy",
    desc: "Triangular Venetian bar snack — soft white bread with crusts removed, generously stuffed.",
    key: ["Soft white bread, no crusts", "Mayonnaise", "Tuna + egg, or prosciutto + artichoke", "Cut into triangles"] },
  { file: "06_shawarma.png", name: "Shawarma", country: "Middle East",
    desc: "Spit-roasted spiced meat shaved off the rotisserie and tucked into pita with fresh toppings.",
    key: ["Pita or flatbread", "Marinated chicken, lamb, or beef", "Tomato, onion, parsley", "Tahini & garlic sauce"] },
  { file: "07_pambazo.png", name: "Pambazo", country: "Mexico",
    desc: "Bread dipped in red guajillo sauce, stuffed with chorizo and potato. Veracruz street food.",
    key: ["Pambazo or telera roll", "Chorizo + diced potato", "Guajillo chile sauce", "Lettuce, crema, queso fresco"] },
  { file: "08_muffaletta.png", name: "Muffaletta", country: "New Orleans, USA",
    desc: "Round Sicilian loaf piled with cured meats, cheese, and tangy chopped olive salad.",
    key: ["Round sesame muffaletta loaf", "Olive salad (chopped olives + giardiniera)", "Salami, mortadella, ham", "Provolone & Swiss"] },
  { file: "09_chivito.png", name: "Chivito", country: "Uruguay",
    desc: "Uruguay's national sandwich. Steak, ham, bacon, mozzarella, lettuce, mayo — and a fried egg.",
    key: ["Soft roll or ciabatta", "Thin-sliced churrasco steak", "Ham, bacon, mozzarella", "Lettuce, tomato, mayo", "Fried egg on top"] },
  { file: "10_smorrebrod.png", name: "Smørrebrød", country: "Denmark",
    desc: "Denmark's iconic open-face on dense rye, with carefully arranged toppings. 'Buttered bread.'",
    key: ["Dense rye bread (rugbrød)", "Plenty of butter", "Pickled herring + dill, or shrimp + lemon, or roast beef"] },
  { file: "11_spatlo_kota.png", name: "Spatlo (Kota)", country: "South Africa",
    desc: "From Johannesburg — a quarter loaf hollowed out and stuffed to bursting with everything.",
    key: ["Quarter loaf, hollowed", "Slap chips (fries)", "Polony or Russian sausage", "Cheese, atchar, fried egg"] },
  { file: "12_montreal_smoked_meat.png", name: "Montreal Smoked Meat", country: "Canada",
    desc: "Quebec's brisket — brined for weeks, smoked, hand-sliced onto rye with yellow mustard.",
    key: ["Light rye bread", "Montreal smoked meat brisket", "Yellow mustard", "Steam meat to warm before piling"] },
  { file: "13_po_boy.png", name: "Po' Boy", country: "New Orleans, USA",
    desc: "NOLA classic on crisp French bread, supposedly invented in 1929 to feed striking streetcar workers.",
    key: ["Crusty French bread", "Fried shrimp/oysters or roast beef", "Lettuce, tomato, pickles", "Mayonnaise"] },
  { file: "14_fricasse.png", name: "Fricassé", country: "Tunisia",
    desc: "Small fried bun packed with tuna, potato, egg, harissa, and olives. Tunisian picnic favorite.",
    key: ["Fried yeast buns", "Tuna in oil", "Boiled potato + egg", "Harissa, preserved lemon", "Olives, capers"] },
  { file: "15_cuban_sandwich.png", name: "Cuban Sandwich", country: "Cuba / USA",
    desc: "Pressed Cuban bread with ham, roast pork, Swiss, pickles, and mustard. Tampa adds salami.",
    key: ["Cuban bread", "Boiled ham + roast pork", "Swiss cheese", "Pickles, yellow mustard", "Press until crispy"] },
  { file: "16_cucumber_sandwich.png", name: "Cucumber Sandwich", country: "United Kingdom",
    desc: "The dainty afternoon-tea classic. Soft white bread (no crusts), butter, paper-thin cucumber.",
    key: ["Very soft white bread, no crusts", "Softened butter", "Cucumber, peeled & paper-thin", "Salt cucumber, drain, pat dry"] },
  { file: "17_chip_butty.png", name: "Chip Butty", country: "United Kingdom",
    desc: "The unpretentious opposite — buttered white bread wrapped around a pile of hot chips.",
    key: ["Soft white sliced bread", "Lots of butter", "Hot thick-cut chips (fries)", "Ketchup, malt vinegar, or HP sauce"] },
  { file: "18_katsu_sando.png", name: "Katsu Sando", country: "Japan",
    desc: "Panko-fried pork cutlet on pillowy milk bread (shokupan) with tangy tonkatsu sauce.",
    key: ["Shokupan (milk bread), no crusts", "Pork loin cutlet, panko-breaded", "Tonkatsu sauce", "Shredded cabbage", "Karashi or Dijon mustard"] },
  { file: "19_croque_monsieur.png", name: "Croque Monsieur / Madame", country: "France",
    desc: "French café staple: ham + Gruyère + béchamel, pan-fried (top with fried egg = madame).",
    key: ["White sandwich bread", "Thin ham + Gruyère", "Béchamel sauce", "Dijon mustard, butter", "Fried egg for madame"] },
  { file: "20_reuben.png", name: "Reuben", country: "United States",
    desc: "Deli classic claimed by Nebraska and New York. Corned beef, sauerkraut, Swiss, dressing, grilled rye.",
    key: ["Rye bread", "Corned beef", "Sauerkraut, drained", "Swiss cheese", "Russian / Thousand Island dressing"] },
  { file: "21_broodje_haring.png", name: "Broodje Haring", country: "Netherlands",
    desc: "Dutch market-stall classic. Cold salt-cured herring with raw onion in a crusty bun.",
    key: ["Crusty white roll", "Hollandse nieuwe herring", "Diced white onion", "Optional: gherkins"] },
  { file: "22_philly_cheesesteak.png", name: "Philly Cheesesteak", country: "Philadelphia, USA",
    desc: "Thin-shaved ribeye griddled with onions, melted cheese, in a hoagie roll.",
    key: ["Hoagie roll", "Thin-sliced ribeye", "Yellow onion", "Provolone or Cheez Whiz", "Optional: peppers, mushrooms"] },
  { file: "23_choripan.png", name: "Choripán", country: "Argentina",
    desc: "Argentine grill classic — chorizo + pan + chimichurri, born from gaucho asados.",
    key: ["Crusty baguette", "Argentine/Spanish chorizo", "Chimichurri (parsley, garlic, vinegar, oil)", "Optional: yellow mustard"] },
  { file: "24_falafel_pita.png", name: "Falafel Pita", country: "Middle East",
    desc: "Crispy chickpea fritters in warm pita with salad and tahini. Vegetarian street-food royalty.",
    key: ["Pita pocket", "Falafel (chickpea fritters)", "Tahini sauce", "Tomato, cucumber, lettuce", "Pickled turnips, hot sauce"] },
  { file: "25_lobster_roll.png", name: "Lobster Roll", country: "New England, USA",
    desc: "Maine: cold lobster + mayo. Connecticut: warm lobster + butter. Both on a split-top bun.",
    key: ["Split-top hot dog bun", "Cooked lobster meat", "Butter for buns", "Maine: mayo + lemon + celery", "Connecticut: melted butter"] },
];

export const sandwiches = baseSandwiches.map((s, i) => ({
  id: String(i + 1).padStart(2, "0"),
  ...s,
}));
